layout: {qmk_keyboard: corne_rotated, layout_name: LAYOUT_split_3x6_3}
layers:
  base:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - BACKSPACE
  - {t: LCTRL, h: sticky}
  - A
  - S
  - D
  - F
  - G
  - H
  - J
  - K
  - L
  - ''''
  - {t: RIGHT ALT, h: sticky}
  - {t: LALT, h: sticky}
  - Z
  - X
  - C
  - V
  - B
  - N
  - M
  - ','
  - .
  - /
  - {t: fun, h: sticky}
  - {t: LGUI, h: sticky}
  - lower
  - ENTER
  - SPACE
  - raise
  - {t: RIGHT SHIFT, h: sticky}
  lower:
  - TAB
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - DELETE
  - Gui+ `
  - PAGE UP
  - Gui+ ENTER
  - Sft+ ENTER
  - Ctl+ SPACE
  - '&msc SCRL_UP'
  - LEFT
  - DOWN
  - UP ARROW
  - RIGHT
  - '&caps_word'
  - {t: ▽, type: trans}
  - ''
  - PAGE DOWN
  - Ctl+Sft+ LGUI
  - Sft+Gui+ LEFT ALT
  - ESCAPE
  - '&msc SCRL_DOWN'
  - '&mkp LCLK'
  - HOME
  - END
  - '&mkp RCLK'
  - APP
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - LGUI
  - LEFT SHIFT
  - Sft+ G
  raise:
  - '`'
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - '*'
  - _
  - '-'
  - '~'
  - LCTRL
  - <
  - (
  - '['
  - '{'
  - \
  - /
  - '}'
  - ']'
  - )
  - '>'
  - '&tilde_macro'
  - LALT
  - '&g_'
  - '-'
  - +
  - '='
  - ':'
  - ;
  - '?'
  - '&quotes_space'
  - '&single_quote_space'
  - '&tmux_visual'
  - {t: ▽, type: trans}
  - {t: LGUI, h: sticky}
  - {t: ▽, type: trans}
  - ''
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  fun:
  - {t: ▽, type: trans}
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - F11
  - F12
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: ▽, type: trans}
  - BT CLR
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - CAPS
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: BT DISC, h: '2'}
  - {t: ▽, type: trans}
  - {t: lower, h: toggle}
  - {t: PRINTSCREEN, type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ;
  - BACKSPACE
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  1_hand:
  - Gui+Sft+Ctl+ 3
  - Gui+ `
  - Gui+ {
  - Gui+ }
  - '&tmux_visual'
  - Gui+Sft+ V
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&mmv MOVE_UP'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Gui+Sft+ 5
  - Gui+ Z
  - Gui+ X
  - Gui+ C
  - Gui+ V
  - Gui+Sft+ Z
  - PAGE UP
  - '&mmv MOVE_LEFT'
  - '&mmv MOVE_DOWN'
  - '&mmv MOVE_RIGHT'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Gui+Sft+ 4
  - SPACE
  - Sft+ ENTER
  - Gui+ ENTER
  - ESCAPE
  - BSPC
  - PAGE DOWN
  - '&msc SCRL_LEFT'
  - '&msc SCRL_DOWN'
  - '&msc SCRL_UP'
  - '&msc SCRL_RIGHT'
  - {t: ▽, type: trans}
  - LEFT COMMAND
  - LEFT SHIFT
  - RET
  - '&mkp LCLK'
  - '&mkp RCLK'
  - '&mkp MCLK'
combos:
- p: [40, 41, 39]
  k: {t: fun, h: toggle}
  l: [lower, raise, fun, base, 1_hand]
- p: [1, 2, 3, 4]
  k: {t: 1_hand, h: toggle}
  l: [lower, raise, fun, base, 1_hand]
- p: [19, 20]
  k: ESCAPE
  l: [base, fun, lower, raise, 1_hand]
- p: [15, 16]
  k: ESCAPE
  l: [base, raise, lower, fun, 1_hand]
- p: [14, 15]
  k: ':'
  l: [base, lower, raise, fun, 1_hand]
  - {p: [12, 13], k: "(", l: ["DEF"]}
  - {p: [16, 17], k: ")", l: ["DEF"]}
  - {p: [11, 12], k: "[", l: ["DEF"]}
  - {p: [17, 18], k: "]", l: ["DEF"]}
  - {p: [26, 27], k: "\\", l: ["DEF"]}
  - {p: [27, 28], k: "|", l: ["DEF"]}
