layout: {qmk_keyboard: corne_rotated, layout_name: LAYOUT_split_3x6_3}
layers:
  base:
    - TAB
    - Q
    - W
    - E
    - R
    - T
    - Y
    - U
    - I
    - O
    - P
    - BSPC
    - LALT
    - A
    - S
    - D
    - F
    - G
    - H
    - J
    - K
    - L
    - ";"
    - "'"
    - {t: LSHFT, h: sticky}
    - Z
    - X
    - C
    - V
    - B
    - N
    - M
    - {t: ",", h: comma_morph}
    - {t: ".", h: dot_morph}
    - "/"
    - {t: RSHFT, h: sticky}
    - {t: ESC, h: LGUI}
    - {t: SPACE, h: NAV}
    - {t: TAB, h: ONE_HAND}
    - {t: RET, h: FUN}
    - {t: BSPC, h: NUM}
    - LCTRL

  num:
    - GRAVE
    - "!"
    - "@"
    - "#"
    - "$"
    - "%"
    - "^"
    - "&"
    - "*"
    - "("
    - ")"
    - ''
    - ''
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    - '0'
    - ''
    - ''
    - {t: LCTRL, h: sticky}
    - {t: LALT, h: sticky}
    - {t: LGUI, h: sticky}
    - {t: LSHFT, h: sticky}
    - '&g_'
    - {t: RSHFT, h: sticky}
    - {t: RGUI, h: sticky}
    - {t: RALT, h: sticky}
    - {t: RCTRL, h: sticky}
    - ''
    - ''
    - LGUI
    - SPACE
    - DOT
    - RET
    - BSPC
    - DEL

  nav:
    - GRAVE
    - TMUX_PREV_WINDOW
    - TMUX_NEXT_WINDOW
    - TMUX_LAST_WINDOW
    - TMUX_CHOOSE_WINDOW
    - TMUX_NEW_WINDOW
    - TMUX_JOIN_PREV_WINDOW
    - WH_U
    - WH_D
    - TMUX_COPY_MODE
    - TMUX_PASTE_BUFFER
    - TMUX_CHOOSE_PANE
    - ''
    - {t: LALT, h: sticky}
    - {t: LCTRL, h: sticky}
    - {t: LALT, h: sticky}
    - {t: LGUI, h: sticky}
    - {t: LSHFT, h: sticky}
    - LEFT
    - DOWN
    - UP
    - RIGHT
    - ''
    - ''
    - ''
    - {t: LCTRL, h: sticky}
    - TMUX_ZOOM
    - TMUX_SPLIT_H
    - TMUX_SPLIT_V
    - TMUX_BREAK_PANE
    - TMUX_PREV_PANE
    - HOME
    - PG_UP
    - PG_DN
    - END
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''

  one_hand:
    - LC(SPACE)
    - HOME
    - PG_UP
    - PG_DN
    - END
    - DEL
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {t: LCTRL, h: sticky}
    - RET
    - BSPC
    - DEL
    - TAB
    - ESC
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - {t: LSHFT, h: sticky}
    - LEFT
    - DOWN
    - UP
    - RIGHT
    - INS
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - LGUI
    - SPACE
    - LALT
    - RET
    - BSPC
    - DEL

  fun:
    - ''
    - F1
    - F2
    - F3
    - F4
    - F5
    - F6
    - F7
    - F8
    - F9
    - F10
    - ''
    - ''
    - F11
    - F12
    - PREV
    - PLAY_PAUSE
    - NEXT
    - VOL_DN
    - MUTE
    - VOL_UP
    - SCREEN_RECORD
    - SCREEN_SELECTION
    - ''
    - ''
    - SCREEN_COPY
    - SCREEN_SELECTION_COPY
    - ''
    - ''
    - ''
    - SCREEN_FULL
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''

combos:
  - {p: [31, 32], k: LT, l: [num]}
  - {p: [32, 33], k: GT, l: [num]}
  - {p: [31, 32], k: "(", l: [base]}
  - {p: [32, 33], k: ")", l: [base]}
  - {p: [19, 20], k: "[", l: [base]}
  - {p: [20, 21], k: "]", l: [base]}
  - {p: [19, 20], k: "{", l: [num]}
  - {p: [20, 21], k: "}", l: [num]}
  - {p: [15, 28], k: BSLH, l: [base, num]}
  - {p: [7, 8], k: LS(RET), l: [base, num]}
  - {p: [8, 9], k: TILDE_SPACE, l: [base, num]}
  - {p: [14, 15], k: LC(SPACE), l: [base, num]}
  - {p: [16, 15], k: LG(K), l: [base]}
  - {p: [2, 15], k: EXCL, l: [base, num]}
  - {p: [2, 14], k: AT, l: [base, num]}
  - {p: [3, 15], k: HASH, l: [base, num]}
  - {p: [4, 16], k: DOLLAR, l: [base, num]}
  - {p: [5, 17], k: PERCENT, l: [base, num]}
  - {p: [6, 18], k: CARET, l: [base, num]}
  - {p: [7, 19], k: AMPERSAND, l: [base, num]}
  - {p: [8, 20], k: ASTERISK, l: [base, num]}
  - {p: [4, 3], k: UNDER, l: [base, num]}
  - {p: [15, 27], k: MINUS, l: [base, num]}
  - {p: [2, 3], k: QMARK, l: [base, num]}
  - {p: [28, 27], k: EQUAL, l: [base, num]}
  - {p: [16, 3], k: GRAVE, l: [base, num]}
  - {p: [18, 30], k: PIPE, l: [base, num]}
  - {p: [27, 26], k: SEMI, l: [base, num]}
  - {p: [16, 15], k: SEMI, l: [base, num]}
  - {p: [16, 28], k: PLUS, l: [base, num]}
  - {p: [19, 31], k: TILDE, l: [base, num]}
  - {p: [19, 8], k: QTSPC, l: [base, num]}
  - {p: [20, 31], k: FSLH, l: [base, num]}
